### ISSUE TITLE
Instructions are terrible.

### ISSUE THREAD

**Issue by Learoy1** [macdylan/sm2uploader#3]
Most of us aren't coders, we can't guess what to do with the files please provide adequate instructions.

**Comment by apphead** [comment]
Being friendly and a thank would have been more appropriate. Guess you couldn't code it yourself,  right 👍?

But since you asked, there are good instructions here:
https://github.com/leandrolima-nyc/SnapmakerJ1#j1-auto-upload-by-kanocz

**Comment by macdylan** [comment]
I'm sorry that this is a hobby project, and I didn't spend much time at the instructions, because it's a command-line tool that doesn't need to be explained to most users who think they need it.

Btw, [J1-Upload](https://github.com/kanocz/j1upload) is a great project that I use it almost every day ❤️
